# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: ciroh-ua-website-ci

on:
  push:
    branches: ["main"]
    tags:
      - 'production-*'
  workflow_call:
    # Map the workflow outputs to job outputs
    # https://docs.github.com/en/github-ae@latest/actions/using-workflows/reusing-workflows
  
      
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
  
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
       fetch-depth: 0
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Generate version
      id: version
      run: echo "::set-output name=VERSION::$(date +'%Y%m%d-%H%M%S')"

    - name: Install dependencies
      run: npm ci

    
    - name: Set build target
      id: build-target
      run: |
          if [[ "${{ github.ref }}" == refs/tags/production-* ]]; then
            echo "DEPLOY_ENV=production" >> $GITHUB_ENV
            echo "Building for PRODUCTION environment"
          else
            echo "DEPLOY_ENV=staging" >> $GITHUB_ENV
            echo "Building for STAGING environment"
          fi
          
          echo "VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV
          echo "${{ env.VERSION }}" > version.txt

    - name: Configure baseUrl
      run: |
        # Create a backup of the original config
        cp docusaurus.config.js docusaurus.config.js.bak
        
        # Use sed to replace the baseUrl value
        if [[ "${{ env.DEPLOY_ENV }}" == "staging" ]]; then
          echo "Setting baseUrl for staging"
          sed -i 's|baseUrl: '\''\/'\''|baseUrl: '\''/docuhub-staging/'\''|g' docusaurus.config.js
          # Or if your config uses double quotes:
          sed -i 's|baseUrl: "\/"|baseUrl: "\/docuhub-staging\/"|g' docusaurus.config.js
        else
          echo "Setting baseUrl for production"
          sed -i 's|baseUrl: '\''\/[^'\'']*'\''|baseUrl: '\''\/'\''|g' docusaurus.config.js
          # Or if your config uses double quotes:
          sed -i 's|baseUrl: "\/[^"]*"|baseUrl: "\/"|g' docusaurus.config.js
        fi
        
        # Show the changed config
        echo "Modified docusaurus.config.js:"
        cat docusaurus.config.js

    # Build the site
    - name: Build website
      run: npm run build
        
    - uses: actions/upload-artifact@v4
      with:
        name: version
        path: version.txt
        
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4
      with:
        # Artifact name
        name: build
        #name: ${{env.GitVersion_SemVer}}
        # A file, directory or wildcard pattern that describes what to upload
        path: build/
        # The desired behavior if no files are found using the provided path.

    - name: Create release
      uses: actions/create-release@v1
      id: create_release
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          tag_name: v${{steps.version.outputs.VERSION}}
          release_name: Release v${{steps.version.outputs.VERSION}}
          draft: false
          prerelease: false
