name: ciroh-ua-website-pr-staging
on:
  pull_request:
    branches: ["*"]
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    
    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - name: Checkout PR Branch
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Generate preview path
      id: preview_path
      run: |
        PR_NUMBER=${{ github.event.pull_request.number }}
        echo "PREVIEW_PATH=docuhub-staging/docuhub-staging/pr-${PR_NUMBER}" >> $GITHUB_ENV
        
    - name: Configure DocuHub for preview
      run: |
        # Update base URL for preview environment
        sed -i "s#baseUrl: '/'#baseUrl: '/${{ env.PREVIEW_PATH }}/'#" docusaurus.config.js
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build
      run: npm run build

    - name: Checkout staging repository
      uses: actions/checkout@v3
      with:
        repository: 'arpita0911patel/docuhub-staging'  # Replace with your staging repository
        token: ${{ secrets.STAGING_REPO_TOKEN }}
        path: 'staging-repo'

    - name: Deploy to staging repository
      run: |
        # Remove old preview if it exists and copy new build
        rm -rf staging-repo/${{ env.PREVIEW_PATH }}
        mkdir -p staging-repo/${{ env.PREVIEW_PATH }}
        cp -r build/* staging-repo/${{ env.PREVIEW_PATH }}/
        
        # Configure Git
        cd staging-repo
        git config user.name "GitHub Actions Bot"
        git config user.email "actions@github.com"
        
        # Commit and push changes
        git add .
        git commit -m "Deploy PR #${{ github.event.pull_request.number }} preview"
        git push
        
    - name: Comment PR
      uses: actions/github-script@v6
      with:
        script: |
          const preview_url = 'https://arpita0911patel.github.io/docuhub-staging/${{ env.PREVIEW_PATH }}';
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `📝 PR Preview deployed!\n\nYou can preview this PR at: ${preview_url}`
          })
